version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - manticore
    environment:
      - APACHE_RUN_USER=#1000

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.8
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-orders_db}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  manticore:
    image: manticoresearch/manticore:latest
    container_name: manticore_search
    ports:
      - "${MANTICORE_HTTP:-9308}:9308"
      - "${MANTICORE_MYSQL:-9306}:9306"
    volumes:
      - manticore_data:/var/lib/manticore

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PMA_PORT:-11097}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    depends_on:
      - db

volumes:
  dbdata:
    driver: local
  manticore_data:
    driver: local