source orders_src
{
    type            = mysql
    sql_host = db
    sql_user = laravel
    sql_pass = secret
    sql_db   = orders_db
    sql_port = 3306

    sql_query = \
        SELECT id, number, email, client_name, client_surname \
        FROM orders
}

index orders
{
    source = orders_src
    path   = /var/lib/manticore/data/orders

    min_word_len = 2
}

source orders_src
{
    type = mysql

    sql_host = db
    sql_user = laravel
    sql_pass = secret
    sql_db   = orders_db
    sql_port = 3306

    sql_query = \
        SELECT id, number, email, client_name, client_surname \
        FROM orders

    sql_attr_uint = id
    sql_field_string = number
    sql_field_string = email
    sql_field_string = client_name
    sql_field_string = client_surname
}

searchd
{
    listen = 9306:mysql41
    listen = 9308:http

    log = /var/lib/manticore/log/searchd.log
    query_log = /var/lib/manticore/log/query.log
    pid_file = /var/lib/manticore/searchd.pid
}
